name: Build GERMLINE
on:
  pull_request:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name for the release. If omitted, just runs build and test."
        required: false
        type: string
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: make germline
      - name: Test
        run: make test
      - name: Release
        uses: softprops/action-gh-release@v2
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name != null }}
        with:
          files: |
            germline
            germline.md5
          make_latest: true
          tag_name: ${{ inputs.tag_name }}
