name: Build GERMLINE
on:
  pull_request:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name for the release"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: make germline
      - run: make test
      - uses: softprops/action-gh-release@v2
#        if: startsWith(github.ref, 'refs/tags/')
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name != null }}
        with:
          files: |
            germline
            germline.md5
          make_latest: true
          tag_name: ${{ inputs.tag_name }}
